version: '2'

services:
  iot-api:
    image: node:10.15.3-alpine
    depends_on:
      - iot-db
    container_name: iot-api
    volumes:
      - iot_api_node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MONGO_DB_HOST=iot-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=iot
    command: yarn dev

  iot-db:
    image: mongo
    container_name: iot-db
    ports:
      - 27017:27017
    volumes:
      - iot_mongo_db:/data/db

volumes:
  iot_api_node_modules:
    external: true
  iot_mongo_db:
    external: true
